"""Dashboard template — dark-theme HTML scaffold with ECharts for save_dashboard().

Extracted from scratchpad_boot.py to keep the boot script lean. Imported by the
scratchpad subprocess at runtime (PYTHONPATH includes the anton package root).
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# CSS — refined dark theme matching the investment dashboard reference style
# ---------------------------------------------------------------------------

DASHBOARD_CSS = """\
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
body{background:#0d1117;color:#e6edf3;font-family:system-ui,-apple-system,'Segoe UI',sans-serif;padding:32px;max-width:1400px;margin:0 auto;line-height:1.6}
h1{font-size:22px;font-weight:700;margin-bottom:4px}
h2{font-size:11px;font-weight:600;margin:24px 0 10px;color:#8b949e;letter-spacing:.1em;text-transform:uppercase}
.subtitle{color:#8b949e;font-size:13px;margin-bottom:24px}

/* KPI cards */
.kpi-row{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:24px}
.kcard{background:#161b22;border:1px solid #30363d;border-radius:12px;padding:14px 18px;flex:1;min-width:120px}
.klabel{color:#8b949e;font-size:10px;letter-spacing:.07em;text-transform:uppercase;margin-bottom:4px}
.kval{font-size:20px;font-weight:700;margin:3px 0}
.ksub{color:#8b949e;font-size:11px}

/* Chart cards */
.card{background:#161b22;border:1px solid #30363d;border-radius:14px;padding:22px;margin-bottom:18px}
.chart{width:100%;height:420px}
.chart-tall{width:100%;height:500px}
.chart-sm{width:100%;height:360px}

/* Layout */
.grid-2{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin-bottom:18px}
@media(max-width:960px){.grid-2{grid-template-columns:1fr}}

/* Tables */
table{width:100%;border-collapse:collapse;font-size:13px}
thead tr{color:#8b949e;text-align:left;border-bottom:1px solid #30363d}
td,th{padding:9px 8px;border-bottom:1px solid #30363d}
tr:hover td{background:rgba(255,255,255,0.02)}

/* Utilities */
.dot{display:inline-block;width:10px;height:10px;border-radius:50%;margin-right:8px;vertical-align:middle}
.badge{display:inline-block;padding:3px 10px;border-radius:20px;font-size:11px;font-weight:700;margin-left:8px}
.footer{color:#8b949e;font-size:11px;margin-top:20px;text-align:center;line-height:1.8}
"""

# ---------------------------------------------------------------------------
# JS preamble — color palette, makeChart() helper, baseTheme
# ---------------------------------------------------------------------------

DASHBOARD_JS_PREAMBLE = """\
const BG='#0d1117',SURFACE='#161b22',BORDER='#30363d',TEXT='#e6edf3',MUTED='#8b949e';
const GREEN='#34d399',BLUE='#60a5fa',YELLOW='#f59e0b',RED='#f87171';
const PURPLE='#a78bfa',ORANGE='#fb923c',TEAL='#2dd4bf',PINK='#f472b6';

const baseTheme={
  backgroundColor:SURFACE,
  textStyle:{color:TEXT,fontFamily:'system-ui,sans-serif'},
  axisLine:{lineStyle:{color:BORDER}},
  splitLine:{lineStyle:{color:BORDER,opacity:0.6}},
  tooltip:{backgroundColor:'#1e2a3a',borderColor:BORDER,textStyle:{color:TEXT}},
};

function makeChart(id){
  const el=document.getElementById(id);
  const c=echarts.init(el,null,{renderer:'canvas'});
  window.addEventListener('resize',()=>c.resize());
  return c;
}
"""

# ---------------------------------------------------------------------------
# Full HTML template — uses {placeholders} for .format()
# Double braces {{ }} escape literal braces in f-strings / .format()
# ---------------------------------------------------------------------------

DASHBOARD_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title}</title>
<script src="https://cdn.jsdelivr.net/npm/echarts@5/dist/echarts.min.js"></script>
{extra_head}
<style>
{css}
</style>
</head>
<body>
<h1>{title_html}</h1>
<div class="subtitle">{subtitle}</div>
{body}
<div class="footer">Generated by Anton</div>
<script>
{js_preamble}
</script>
{extra_scripts}
</body>
</html>
"""


# ---------------------------------------------------------------------------
# save_dashboard() — the function injected into scratchpad namespace
# ---------------------------------------------------------------------------

def save_dashboard(
    filename: str,
    title: str,
    body: str,
    *,
    subtitle: str = "",
    title_html: str = "",
    extra_head: str = "",
    extra_scripts: str = "",
    data_js: dict | None = None,
    open_browser: bool = True,
) -> str:
    """Save a complete dark-themed dashboard HTML and open it in the browser.

    Args:
        filename: Output filename (e.g. 'portfolio.html'). Saved to .anton/output/.
        title: Dashboard title shown in <title> and <h1> (unless title_html overrides).
        body: Inner HTML — chart containers, KPI cards, tables, JS init code, etc.
            The outer page structure (head, CSS, ECharts CDN, color palette, makeChart
            helper, baseTheme) is provided automatically.
        subtitle: Optional subtitle below the title. Timestamp is appended automatically.
        title_html: Optional rich HTML for the <h1> (badges, icons). Falls back to title.
        extra_head: Additional <head> content (extra CSS, script tags).
        extra_scripts: Additional <script> blocks placed before </body>. Wrap in
            <script>...</script> tags. The JS preamble (color constants, makeChart,
            baseTheme) is already available — your code can use them directly.
        data_js: Optional dict — serialized as JS and saved as a companion _data.js file.
            Referenced as global `D` in your scripts (D.charts.*, D.kpis.*, etc.).
        open_browser: Whether to auto-open in the browser (default True).

    Returns:
        Absolute path to the saved HTML file.
    """
    import datetime as _dt
    import json as _json
    import os as _os
    import webbrowser as _wb

    output_dir = _os.path.join(_os.getcwd(), ".anton", "output")
    _os.makedirs(output_dir, exist_ok=True)
    html_path = _os.path.join(output_dir, filename)

    # Handle data_js: serialize dict to companion JS file
    data_script = ""
    if data_js is not None:
        data_filename = filename.rsplit(".", 1)[0] + "_data.js"
        data_path = _os.path.join(output_dir, data_filename)
        js_content = "const D = " + _json.dumps(data_js, default=str) + ";"
        with open(data_path, "w", encoding="utf-8") as f:
            f.write(js_content)
        data_script = f'<script src="{data_filename}"></script>'
        print(f"Data: {data_path} ({_os.path.getsize(data_path):,} bytes)")

    # Build subtitle with timestamp
    now = _dt.datetime.now().strftime("%Y-%m-%d %H:%M")
    full_subtitle = f"{subtitle} &middot; {now}" if subtitle else now

    # Inject data script into extra_head
    if data_script:
        extra_head = data_script + "\n" + extra_head

    html = DASHBOARD_TEMPLATE.format(
        title=title,
        title_html=title_html or title,
        subtitle=full_subtitle,
        body=body,
        css=DASHBOARD_CSS,
        js_preamble=DASHBOARD_JS_PREAMBLE,
        extra_head=extra_head,
        extra_scripts=extra_scripts,
    )

    with open(html_path, "w", encoding="utf-8") as f:
        f.write(html)

    abs_path = _os.path.abspath(html_path)
    size = _os.path.getsize(abs_path)
    print(f"Dashboard saved: {abs_path} ({size:,} bytes)")

    if open_browser:
        _wb.open(f"file://{abs_path}")
        print("Opened in browser.")

    return abs_path
